markdown:         kramdown
highlighter:      rouge
permalink:        /vol/:title/

title:            "Zac"
url:              http://zaac.ml
feed:             /feed.xml
author:
    name:         Zac
description:      "ZAAAAAAAAAC"
copyright:        "CopryRight 2017"
headdesc:         "ZAAAAAAAAAC"
headkeys:         "ZAAAAAAAAAC"
